const express = require("express");

const JapaneseProgress = require("../models/JapaneseProgress");
const JapaneseAccessCode = require("../models/JapaneseAccessCode");
const jishoLookup = require("../utils/jishoLookup");

// Public routes for the guest Japanese learning page (/learn). No admin
// session — the access code (generated by an admin in the Students tab) is
// the credential, sent on every request as the x-learn-code header. Progress
// is stored in JapaneseProgress under adminId "learn:<code>" so admins can
// watch it.
const router = express.Router();

const MAX_ITEMS = 5000;
const isObj = (v) => v && typeof v === "object" && !Array.isArray(v);

function toState(doc) {
  if (!doc) return null;
  return {
    srs: doc.srs || {},
    stats: doc.stats || {},
    settings: doc.settings || {},
    words: Array.isArray(doc.words) ? doc.words : [],
    sentences: Array.isArray(doc.sentences) ? doc.sentences : [],
    updatedAt: doc.clientUpdatedAt || 0,
  };
}

const normCode = (c) => String(c || "").trim().toUpperCase().slice(0, 16);

// Simple in-memory rate limit so codes can't be brute-forced.
// Only FAILED code checks count toward the limit, so an active studying
// guest is never throttled but brute-forcing codes is.
const attempts = new Map();
const WINDOW = 10 * 60 * 1000;
const MAX_FAILS = 15;
function tooManyFails(ip) {
  const a = attempts.get(ip);
  return !!a && Date.now() - a.t <= WINDOW && a.n >= MAX_FAILS;
}
function bumpFails(ip) {
  const now = Date.now();
  const a = attempts.get(ip);
  if (!a || now - a.t > WINDOW) {
    if (attempts.size > 5000) attempts.clear();
    attempts.set(ip, { t: now, n: 1 });
  } else a.n++;
}

async function requireCode(req, res, next) {
  try {
    const code = normCode(req.get("x-learn-code"));
    if (!code) return res.status(401).json({ success: false, message: "Missing access code" });
    if (tooManyFails(req.ip)) return res.status(429).json({ success: false, message: "Too many attempts" });
    const doc = await JapaneseAccessCode.findOne({ code, active: true }).lean();
    if (!doc) {
      bumpFails(req.ip);
      return res.status(401).json({ success: false, message: "Invalid or revoked access code" });
    }
    req.learnCode = doc;
    JapaneseAccessCode.updateOne({ _id: doc._id }, { $set: { lastActiveAt: Date.now() } }).catch(() => {});
    next();
  } catch (err) {
    console.error("learn code check error:", err.message);
    res.status(500).json({ success: false, message: "Server error" });
  }
}

router.post("/learn/verify", async (req, res) => {
  try {
    if (tooManyFails(req.ip)) return res.status(429).json({ success: false, message: "Too many attempts — wait a few minutes" });
    const code = normCode((req.body || {}).code);
    if (!code) return res.status(400).json({ success: false, message: "Enter your access code" });
    const doc = await JapaneseAccessCode.findOne({ code, active: true }).lean();
    if (!doc) {
      bumpFails(req.ip);
      return res.status(401).json({ success: false, message: "That code isn't valid — check it with the person who gave it to you" });
    }
    JapaneseAccessCode.updateOne({ _id: doc._id }, { $set: { lastActiveAt: Date.now() } }).catch(() => {});
    res.json({ success: true, code: doc.code, label: doc.label || "" });
  } catch (err) {
    console.error("learn/verify error:", err.message);
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/learn/state", requireCode, async (req, res) => {
  try {
    const doc = await JapaneseProgress.findOne({ adminId: "learn:" + req.learnCode.code }).lean();
    res.json({ success: true, state: toState(doc) });
  } catch (err) {
    console.error("learn/state load error:", err.message);
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.put("/learn/state", requireCode, async (req, res) => {
  try {
    const b = req.body || {};
    const update = {
      srs: isObj(b.srs) ? b.srs : {},
      stats: isObj(b.stats) ? b.stats : {},
      settings: isObj(b.settings) ? b.settings : {},
      words: Array.isArray(b.words) ? b.words.slice(0, MAX_ITEMS) : [],
      sentences: Array.isArray(b.sentences) ? b.sentences.slice(0, MAX_ITEMS) : [],
      clientUpdatedAt: Number(b.updatedAt) || Date.now(),
    };
    const doc = await JapaneseProgress.findOneAndUpdate(
      { adminId: "learn:" + req.learnCode.code },
      { $set: update },
      { new: true, upsert: true, setDefaultsOnInsert: true },
    ).lean();
    res.json({ success: true, state: toState(doc) });
  } catch (err) {
    console.error("learn/state save error:", err.message);
    res.status(500).json({ success: false, message: "Server error" });
  }
});

router.get("/learn/lookup", requireCode, jishoLookup);

module.exports = router;
