// Lightweight Telegram update listener.
//
// The bot otherwise only *sends* messages. To let each admin link their own
// chat we need to *receive* the confirmation they send from inside Telegram.
// This long-polls getUpdates (no webhook / public URL required) and, when an
// admin sends the bot a link code (via the "/start <code>" deep link or by
// typing "/link <code>"), captures their chat_id and stores it against the
// admin whose pending code matches.
//
// Safe to start unconditionally: it no-ops when TG_TOKEN is unset and backs
// off on errors (including the 409 returned if a webhook or another poller is
// already consuming updates).
const axios = require("axios");

const { linkTelegramByCode } = require("./admins");
const { sendToChat, getMe } = require("./telegram");

const LONG_POLL_SECONDS = 50;
const ERROR_BACKOFF_MS = 5000;

const state = {
  started: false,
  running: false,
  offset: 0,
  botUsername: null,
};

// Pull a "code" out of an incoming message. Supports the deep-link form
// ("/start ABCD1234"), an explicit "/link ABCD1234", or a bare code typed on
// its own. Returns the raw token (validated later by linkTelegramByCode).
function extractCode(text) {
  const trimmed = String(text || "").trim();
  if (!trimmed) return null;

  const startMatch = trimmed.match(/^\/start(?:@\w+)?\s+(\S+)/i);
  if (startMatch) return startMatch[1];

  const linkMatch = trimmed.match(/^\/link(?:@\w+)?\s+(\S+)/i);
  if (linkMatch) return linkMatch[1];

  // A bare code on its own line (8 hex chars as generated by startTelegramLink,
  // but we stay lenient and let the store decide if it actually matches).
  if (/^[A-Za-z0-9]{4,16}$/.test(trimmed)) return trimmed;

  return null;
}

async function handleMessage(message) {
  const text = message?.text;
  const chatId = message?.chat?.id;
  if (chatId === undefined || chatId === null) return;

  const fromUsername = message?.from?.username || "";

  // A bare "/start" with no code: greet and explain what to do.
  if (/^\/start(?:@\w+)?\s*$/i.test(String(text || ""))) {
    await sendToChat(
      chatId,
      "👋 Welcome! To link this Telegram to your admin account, open the " +
        "Settings page in the admin panel, tap “Connect Telegram”, and use " +
        "the button (or send /link followed by the code shown there).",
    );
    return;
  }

  const code = extractCode(text);
  if (!code) return;

  try {
    const linked = await linkTelegramByCode(code, chatId, fromUsername);
    if (linked) {
      await sendToChat(
        chatId,
        `✅ Linked! This chat is now connected to admin “${linked.username}”. ` +
          "You'll receive Telegram notifications for the orders you create.",
      );
    } else {
      await sendToChat(
        chatId,
        "⚠️ That link code is invalid or has expired. Open the Settings page " +
          "in the admin panel and tap “Connect Telegram” to get a fresh code.",
      );
    }
  } catch (err) {
    console.error("telegramBot link error:", err.message);
  }
}

async function poll() {
  const token = process.env.TG_TOKEN;
  if (!token) return;

  while (state.running) {
    try {
      const res = await axios.get(
        `https://api.telegram.org/bot${token}/getUpdates`,
        {
          params: {
            offset: state.offset || undefined,
            timeout: LONG_POLL_SECONDS,
            allowed_updates: ["message"],
          },
          timeout: (LONG_POLL_SECONDS + 10) * 1000,
        },
      );

      const updates = res.data?.result || [];
      for (const update of updates) {
        // Advance the offset past every update we see so it isn't redelivered,
        // even ones we don't act on.
        state.offset = update.update_id + 1;
        if (update.message) {
          await handleMessage(update.message);
        }
      }
    } catch (err) {
      const data = err.response?.data;
      console.error("telegramBot poll error:", data || err.message);
      // 409 = a webhook or another getUpdates consumer is active. Back off and
      // retry rather than hammering the API.
      await new Promise((r) => setTimeout(r, ERROR_BACKOFF_MS));
    }
  }
}

// Begin listening. Idempotent — calling start() more than once is a no-op.
function start() {
  if (state.started) return;
  state.started = true;

  if (!process.env.TG_TOKEN) {
    console.log("telegramBot: TG_TOKEN not set — link listener disabled");
    return;
  }

  state.running = true;
  getMe()
    .then((me) => {
      if (me?.username) {
        state.botUsername = me.username;
        console.log(`telegramBot: listening as @${me.username}`);
      }
    })
    .catch(() => {});

  poll();
}

function getBotUsername() {
  return state.botUsername;
}

module.exports = { start, getBotUsername };
